# Generated by Django 3.1.7 on 2021-02-27 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0004_brand'),
        ('products', '0004_auto_20210227_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorys.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_family',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Black', 'Black'), ('Grey', 'Grey'), ('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Cyan', 'Cyan'), ('Green', 'Green'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Orange', 'Orange'), ('Purple', 'Purple')], max_length=10, null=True),
        ),
    ]
