# Generated by Django 3.1.7 on 2021-02-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0002_auto_20210227_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='primarycategory',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='secondarycategory',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
